# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Validate no assets
      run: test ! -d ./src/generated
    - name: Generate assets
      run: ./gradlew runData --no-daemon --max-workers 1
    - name: Validate assets
      run: test -d ./src/generated -a -f ./src/generated/resources/.cache/cache
    - name: Build with Gradle
      run: ./gradlew build
    - name: capture build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: OakOres-Forge-Dev
        path: build/libs/
