name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for your feedback, I (OakBricks) will try to fix your issue ASAP!'
        pr-message: 'Thanks for your pull request, I (OakBricks) will consider if your pull request is worthy of being merged!'
